simplexes_ignored: 一㇀㇒丶

simplexes:
    丨: 丨丿亅乚𠄌㇂㇝
    ㇇: 𠃌乛𠃍㇇了
    ⺄: 乁⺄㇈乙
    ㄥ: 𠃊𠃋㇄𡿨
    ㇏: 乀㇏㇝
    ル: 人八𠆢丷刂儿入
    十: 𠂇十𬺰
    ㄡ: 又女夂夊
    二: 二𠄠冫⺀𠄟𰀪
    三: 氵三
    ㄇ: 冂⺆冖卩几𠘨𠘧
    力: 力刀九
    ⺊: 卜⺊
    七: 匕𠤎七𫠠乜
    ㄩ: 凵丩
    ㄨ: 㐅乂
    ㄏ: 厂𠂆
    弓: 𠃑㇉讠弓
    ㄈ: 匚匸
    ロ: 口囗
    丰: 扌𰀁丯丰
    廾: 廾艹
    大: 大尢
    小: 小忄𡭔⺌心灬⺗
    ア: 已㔾巳尸ㄗ阝𰆊乃 # 巴
    日: 日曰丑
    コ: «50»«14»
    x: 卍凸凹

simplexes_reserve:
    申: 毋毌田申甲电
    月: 月⺝⺼
    目: 目且耳罒皿

compounds:
    辶: ㇇㇐
    廴: ㇇㇇㇐
    母: 日二
    𨈐: ㇒口㇒
    身: ㇒目㇒
    万: 一力
    民: ㄗ𫠠
    氏: ㄏ𫠠
    𧘇: 亻乀㇒

substitutes1:
    ⿰㇒乛: ⺈ # 尔欠亇
    ⿰丿丨: 丌 # 廾介井弗齐丌乔养氘
    ⿱丶丶: ⺀ # 雨舟𠔾摔蟀眔
    ⿱一𠃋: ㄈ
    ⿻一𠃋: ㄈ # 车东𫠣
    ⿰㇀丶: ㇀ # 虫
    ⿰丿丿: リ # 勿𠃓
    ⿰丿㇄: ル
    ⿰丿亅: ⺆ # 亦赤
    ⿰丿𠃌: 勹 # 𠮠𫠤
    ⿻㇂㇒: 乂
    ⿱𠃊丆: 爿
    ⿰丨丨: 刂
    ⿻⿰丨丨丷: ⺌
    ⿻口⿰丨丨: 罒
    ⿻口刂: 罒
    ⿻口丿: 中 # 免史晚兔勉挽冤冕娩
    ⿻{43}亅: 尹
    ⿲丿二丨: 井 # 齊斉
    ⿵冂⺀: 月 # 兪箭剪煎翦
    ⿵⺆⺀: 月 # 廟萠
    ⿴{11}亅: 氺
    ⿻日丿: 甲 # 卑俾鬼牌碑脾啤婢痺髀裨稗捭睥鼙
    ⿸⿻口丿乚: 兄 # 免晚兔勉挽冤冕娩
    ⿴{11}丨: 氺
    ⿱一丰: 丰 # 拜拝
    ⿱𠃑大: 夬
    ⿰𰀪𰀠: 水
    ⿱㇒𰀠: «15»
    ⿻𠃋丿: 𠂇

substitutes2: 
    丅⿵冂: 帀
    ⿱一⿱一: ⿱二
    ⿱一⿳一: ⿳二
    ⿱一⿱㇒: ⿱丆
    ⿲丨丨: ⿰刂
    一⿻一: 二
    一⿱一: 二

---
ids:
    «1»: ⿹⿺㇉一灬	bottom of 廌焉舃
    «2»: ⿱⺈𫩏	top of 免象
    «3»: ⿱⺈⿵冂人	top of 夐
    «4»: ⿱⿻⿰丨丨丷冖	top of 䝉𫎇
    «5»: ？	left of 叚
    «6»: ？	left of 段
    «7»: ？	top of 專惠
    «8»: ⿻⿱㇒一乚	right of 扥
    «9»: ⿱⿰㇒㇖丨	right of 𪟳𪝪
    «10»: ⿻⿻㇈丿丶	right of 巩 [T source glyph]
    «11»: ⿰⿱丶㇀⿱㇒丶	bottom of 軣
    «12»: ？	right of 龍
    «13»: ⿸⿰丿⿱⺊⺂七	outside of 虍
    «14»: ？	top of 𡕡
    «15»: ⿻𱍸㇒	bottom-right of 旅
    «16»: ⿲⿺𠄌⺀⿺𠄌⺀㇂	bottom of 鼠
    «17»: ？	left of 剆 [G source glyph]
    «18»: ？	left of 即
    «19»: ？	right of 㤤
    «20»: 丸	right of 執 [G source glyph]
    «21»: ？	top of 祭豋
    «22»: ⿺㇉一	outside of 与
    «23»: ？	inside of 與
    «24»: ？	right of 水
    «25»: ？	bottom
    «26»: ？	top of 韲
    «27»: ？	bottom of 𤣥
    «28»: ⿻弋一	outside of 武貮
    «29»: ⿻弋𢆶	outside of 幾畿
    «30»: ？	top of 彔
    «31»: ⿴囗⿻𰀪丶	bottom of 卥
    «32»: ⿱⿻𠮛⿰丨丨冖	top of 𣓝
    «33»: ？	bottom of 雋
    «34»: ⿹勹丿	bottom of 䇖
    «35»: ⿻几𠄠	right of 𠖵
    «36»: 	top of 𠢘㥑
    «37»: ⿱⺊冖	top of 睿
    «38»: ⿱𰀉冖	top of 橐
    «39»: ？	left of 卬
    «40»: ？	right of 𩤷
    «41»: ⿻𦉫𠄠	left of 𠜂 [T-form of 𠕋]
    «42»: 彐	top of 录
    «43»: ⺕	top of 㚑
    «44»: ⿱十冖	top of 孛
    «45»: ？	left of 北 [G source glyph]
    «46»: ⿻日乚	bottom of 竜
    «47»: ？	outside of 鳥島
    «48»: 㐄	bottom of 年 [J-form of 㐄]
    «49»: ⿰丨丿	left of 帅
    «50»: ？	top right of 叚
    «51»: ？	outside of 馬
    «52»: ？	outside of 马
    «53»: ？	outside of 鸟岛
    «54»: ？	outside of 烏
    «55»: ？	outside of 鹿慶
    «56»: ？	top of 無
    «57»: ？	outside of 在
    «58»: ⿰«39»丶	top left of 留
    «59»: ？	bottom of 舄
    «60»: ？	outside of 龜 [H source glyph]
    «61»: ？	outside of 臧
    «62»: ？	bottom of 華
    «63»: 舟	left of 𦩳
    «64»: ？	bottom left of 龜 [G source glyph]
    «65»: ？	bottom right of 龜 [G source glyph]
    «66»: ？	bottom right of 𪚴
    «67»: ⿴⿰丨丨𠄠	middle of 髙 and 𠅘
    «68»: ？	top of 黑
    «69»: ？	outside of 戠
    «70»: ？	inside of 虛
    «71»: ？	left of 𦥑
    «72»: ？	left of 印 [G source glyph]
    «73»: ⿴𠀃三	top of 具
    «74»: ？	middle of 鄕 [J source glyph]
    «75»: ？	bottom left of 爵 [K source glyph]
    «76»: ？	top of 長
    «77»: ？	top of 㒫
    «78»: ⿱⿻口⿰丨丨一	亜 without the top stroke
    «79»: ？	亞 without the top stroke
    «80»: ⿱冖八	top of 罙 [G source glyph]
    «81»: ？	inner part of 𮭷
    «82»: ⿱𦘒一	top of 書
    «83»: ⿳亠丷冖	top of 帝
    «84»: ⿰丿乛	厂 with hooked stroke
    «85»: ⿰丿⿱丶乛	广 with hooked stroke
    «86»: ⿲丶丶丶	first three strokes of 灬
    «87»: ⿳亠口冖	top of 亭
    «88»: ⿵𠆢一	top of 合
    «89»: ？	outside of 𪚧
    «90»: ？	core of 龜 [G source glyph]
    «91»: ？	core of 黽
    «92»: ？	core of 𪚧
    «93»: ⿻昌乚	right of 縄
    «94»: ？	top of 其
    «95»: ⿻尸一	bottom of 𢀞
    «96»: ？	outside of 𭾐
    «97»: ？	bottom right of 𮊫 or right of 戠 without horizontal stroke
    «98»: ⿻一曲	top of 曹
    «99»: ⿻𦉫𠄠	top of 𢘼
    «100»: ？	之 without top stroke
    «101»: ？	left of 癶
    «102»: ？	right of 癶
    «103»: ？	top right of 祭
    «104»: ？	top right of 𥋮
    «105»: ？	top right of 𨄛
    «106»: ？	top of 𡛹
    «107»: ？	middle of 𡙌
    «108»: ？	top of 冎 [G source glyph]
    «109»: ⿻⿱㇒一丿	left of 刋
    «110»: 冂	outside of 𭁟
    «111»: ？	inside of 𭁟
    «112»: ？	outside of 𦥓
    «113»: ⿵冂八	bottom of 𠕉
    «114»: ⿱土八	top of 坴 [G source glyph]
    «115»: ⿻𰀪⺀	top of 𫭣
    «116»: ？	inside top of 鹿慶
    «117»: ⿺𠃊⺊	inside of 𠣏 [G source glyph]
    «118»: ？	outside of 𠁅
    «119»: ⿻己⿱工工	right of 𥛈
    «120»: ⿻弓⿱«50»匚	right of 𤛒 without 口
    «121»: ⿱⺈罒	top of 𣬋

---
remains:
    ?: 亻犭𠂉𠄎㐄及
    ??: 爪出冉曲我車里也
    ⊖: 𫝀𣥂𤓰𬺷𭺫𬺻𧰨𧰧𫝕𨳇𭴺
    ;: ⺈𠂊纟己幺乡饣久攵𤣩礻火牜钅𥫗⺶襾訁釒飠

---
unsorted:
    simp: «100»«24»«52»«84»«27»«39»«43»«48»«25»«23»«45»«58»«20»«71»«117»«86»«42»«108»«10»«67»«76»«11»«15»«72»«95»𠀉«65»«112»«18»«46»«6»«53»瓜«94»«73»«19»«51»«91»«64»«75»«70»«90»«54»«12»«62»«74»豸«47»«40»«98»«79»«7»«68»«17»«16»«26»
    2: 丆亠«88»厶丁丅«22»龴勹丄«100»丂𰛄«24»𠄐«52»𠀁«84»«27»«39»刁巜
    3: 土勺宀«97»彳子寸工广夕«57»巾上亍亡𠫔屮门下«43»士山干𫜹彡个兀«48»弋川丬才之𫝀«25»𰃦龵习于马与𰛅𠂋𭕄千么«23»义𠃓丫𠀃卄«45»丌𰀠«58»«20»丸乞乇卂𠂌«71»彑凡飞«117»«86»𰀃«42»巛𠔼亇刃卫亿丈亏«108»«10»亐𠂎卪叉𭠍𰀂𰀄𡳾𫶧«37»孑𬼽䶹孓
    4: 木戈𠮛王斤方不中龶止耂巨尤云文牙𱼀𫩏殳廿开欠以从犬分戶贝手戸天反𠂒牛化爫元见𡈼龰车𫧇少公予夬为比歹旡夫壬冃勿五今支水气𠬝𭃂内𰀆介父«67»爿斗井冇区户六长太午𠓜片仒尺𣥂友円什专无朩切引卝毛帀办夭𠃜«76»內仑«11»亢屯队书«15»计㓁𠁣𠃛仓韦风卬升勾𰀡允匀尹勻冄仍卅厄𭁟厷巿冈厃𡭕«72»双冗历乏禸«28»互丑収仅凶匂𠀇«44»瓦匹艺«95»肀𱐩𡯃仁冘圡孔丹«113»扎乌币卆𠀉厅幻«65»𠔾攴邓仏凤仇𠔿𠂑夃爻𠠵仆«80»厸丐刈㝉兮尐弔«112»㕚卞仄丏仃㞢仌亓𠤏
    5: 白禾尔尓𤴓可去生示业立正玉甘左他本主尼旦未矢占乍石冋用加龷由戊«18»台宂穴古癶𰃮衤𦓐市令皮圥只𫩑疒代四北龸外对兄平发𢀖头半氺圣打务𢎨𡗗叫𠁤付包世术冬必央司句矛氐弗失召它朮𢆉右布另㐱㐌戋丙东叩疋処𠮥㠯𠮠史乎𠮦号斥刍丘戉仔«46»功㕣处広«6»奴兰击永旧写印鸟𠬤边末𠀐氶龙犯𫢉节卡𠂛«53»氿乐厈弁𰀢犮庁丗仕瓜艾氾刊宁汉辺札𫠣礼讨玄卯幼厉仙𠙻夗巧凷𠙽训叶奶归冊払汇卉圧丝册灭𠕁𩰊𩰋𠮡闪叹𤴔屵卢𦉫匆冚甩汁𠂔冯𡯄丛孕叧圤帅𦘒丕囚𣄼匝氷弘㲺扒氹叨«114»𠀔轧叱汀𦉰龱仟叵夲廵歺匛卮夯仨匃𡚬㞋仞仡囙宄尕艽艿邛
    6: 糸糹有䒑至佢在𦍌艮寺覀米同舌好年自合会各地成行而羊多吅交次先𭤨此那䏍吉虫关刖页全西舟衣聿充安因向再共如吏𠂤回名«94»亥当毎𦥑件产式𧰨后𭷔过列«73»旨百任虍亘吊早吕«82»老死动𢦏𱒃光色臼企争圭收军考并兴«19»仲亦羽𪧷戌机𰁜臣州«2»朿问齐劦亚𠂢刑字𠦏存𢖻兆份気厽缶执𠮷设防则朱华𠔉达决𫇦龹似农血约江廷壮㐫许杀导危両守夅师巩团«83»级𤰔𫡑延𠃧休邦肉宅舛尗忙夷众𭥍划乑幵买尽红灰旬伊负甶弚匈吂𣦼竹尧优乔夹阳刚杂伝𠯂欢刘托网岁«51»庄冲𰢴㓞宇𭃌夸压异孙耒池芝𣎾巟朵屰迅伏冰寻伙戏𢆶伐肋阴汤戎𠅃毕仿爷仰汗尖岂叒夺汚吋𡰯扣«91»«64»吐污闭扱劣𫥞邪穵«75»贞匡肌伪𦣞«70»亙迁迈圳𦈢戍轨朴«90»厌丢奸曳尘汒𰋷匠丟吁帆芒闯𡰪𣲇迄妄㐆«54»牟«1»朽兇丞汝伞孖𫠥乒玑阮奻㚏扛旭汛汲邢囡汙阪祁伎吆𭇁弛芋𠧗𡗞伢𫠤岌芍圩夙汐芊𠅇«31»圪纣䏌兊艸芎𠕽凼刎囟圮汜牝玎纥芏
    7: 你貝系走見呀言吾豕𧾷巠作兑来阿但社每𥃭角完囬𭚧甬求告良时孝辛更即住酉𱥯条谷余位利呆体豆売兌把肖改弟吿进男呂釆束坐囱何还𦣻近没決㐬步呈快甫足囪忍辰対冏形寽两员免间究局投佥技希声志报花𫲸应村却別秀判初君兵低克助壯«87»«12»𰢵矣𰆘𠤕别㣊私否䖝张㦮町批李折找医沒均听役连估材佑赤镸含困攻冷吴远况努𠕒𣏂串𠬶迎严夋抗佛佐扮孚丽县沙夆尾労劳陈床犾乱«62»苏«74»戒围㫗亨伸序坚寿财伯附层𠰅沖纳奂忘児抓壳旱沉吳阻伴亜豸吹旲夾灵怀図岛狂块启呉芸妙泛园抑巫补妥肙«47»坏库杨«40»弄«98»𱥻戻肚孛扶𫲽㳄沈宋災肝抖麦㝴皃纷囲坂呙灾佔杜岐纯𭻾苋弃芳尿皀妨抄杉贡冝«55»圼犹攸宏穷闰劲扯卵亩𦉬𭕆𰤲闲甹忌牢«21»芬岗吞沟纽劫妟坑沃芹吟呎洰吻汪𬎿坊陀纺«38»杆闷«79»芽肠坒罕坎㫖屁冶汰抌狄邱秃甸𦣝坠杖芭坟庇杏禿邑妊灶妓吠芙沛茾龟芯扼汶祀伽吽𬌪牡灼邵闵𰙜皂伶删庐忡杠沐匣孜扳肘抉佘𦔮沁灸芥彷妞岑呑沂吝彤扽邯忒𥃦扲羌乕囤妍汾佗卤汞沅肓芷𫹍㚒汩玖芮𦥔𫝹芩芪佞圻忸汨苁陂劬劭卣岜忤杓芟芡芫芰芾𡕙
    8: 的者門京隹到国固或青其事和雨㝵𫩠靑咅拉長咼果所定法官非明学知直𢆍𦍎周來表具制建使金東受性取𥝢幸𣏟林物些念治«56»卑兩放空於戔並帛昔始实臤𠦝委忩𩙿妾爭罙炎采居易𧈧奇侖育命畀𥃲服帚実府若油房供英参郎店㑒例劵怕注叔往玩画兒卖武夜波限录㚘彔肯单罔变隶宗朋依河斉虎规斦苦松底鱼味亟狀述责昏昌宓«7»«68»罗刻亞担降況版拍卒股质尚转承岩卷享苗忝㐭歩垂备卓欧舍招岡昆𰧭杯坴迫苟怪图典爸岸析屈妻板抱宛妹终券卦衫奉𭁨征范宝斩宜彼抽刺拔届忽佰季忠孟佳狗沓审匋臽耶«17»炒肥枝効玨尙欣坦戾姑押昇贯屆败奄厓呵舎孤枚拂坡择㸚泥姆夌顶肩杲杰奔宙肃贫𢌿尭牧泊迪齿奋兔郑函刷径顷幷乳茂奈泳泪疌咖昍侌浅岳郊佩盲郁囷妮闹净泙炉废帕氛肺垃叁匊凭拘«16»旺泡披丧乖«36»歧𡬠侠沼𧈡昂坪祇弦泣𢼄沽拋㸒𱐍侍黾𤰞拐杭刮𬎾弥陌𫂱枉贤卧肴贪庙糾咒肿泄茅豖沾𲂻沸玫𫵖𤕰叕狐彿怡忿怯坤抨泌帖沫㡀枢苹𠈌斧枕刹炊昗沮茄衬阜迦陏虏陋庚迭宠拙牀帘侈秉枣苑𠣜𧘗侄侃侣咎苛炬畄觅歨臥苔弧甾臾㧜佻呱𡕥拌迢鼡茁拈炙苯佯弩拃昊沱穹竺诣迥宕岱苓虱侗炆苞泓瓮«61»㓤戕抦杼枭沝泯盂庖昕昙杳杵矾籴郅兖妲戽沬泅苫苻軋迤佶坨岢帙怛昀枋泔泠泫泮炏狍玟盱肫苕苜苴茆𠚍
    9: 是既係要相重頁音架亲首品咸為故前政度畐面说剌昜後看県骨食美保信很軍活思指禺点种客持封界神約発娄泉院扁屋洛則革南研俞計将科虽畏単送壴便咪查韋施复省除兪𡿺类派卻总急鬼战娜星某爰昭段柬査巷型城差追结退待统風帝修負叚斿孩亭𦍒室陣怎胡突香曷带春皆洗宣昨㒸哈律変枼觉独飛叟洋皇𦚏耑荅残背威项映显举费庭秋禹耐响草奐括胃迶茶級茍甚轻贵酋乗须染弯紅促毒迷哂奏兹荒昷姿绝厚彖爯紀穿盾津亮逃养挑冒侵适契拜祖勇彦胜専贸𦭝𭴘訂珍帮𨊠㚅临俄茲咠荣怒卸洞削逆钟顺俗垔䙲恨臿祝胞侯巻柔𦔻眉恢炮俊郡尝剑恰柱洪怨冠𡱒宫𡱝柳勁咬迹蚤赴咨炭咱勉貞䚯栄络贲胆𬛸览幽挺贷柏勃挖哀虹柄恒叛屏玲阁宪垚盆狠拾𱬹叙盼柯矩骂盈贺屎珀娃恆狱𱅑胖虐胎厘卽拼枯畑脉迴垣匍牵茫洽耍泵恼砍𱼭郞咢歪軌姚珊茨衍陛浄炳𭣦钦郝姜𬙙洒哉荐咲怠彥昧缸荘贱竿垒胥恍拱奎癸恃拯荆𣢟垫姦帥眇钧柰贰剎炫訇𡇒虾怱茜茵峙洼矜𫥎拭殃浊炯㚇宦闽匧匽姪荔俟奕拴柿垢恪毗笃茸栈茹荧𱭏枷甭盃耷茧荃迸绚闾𣳾俐咿勅恬敄昱盅荀荟孨峦徇柑𦙲俚祗笈荏衿韭𤰭垠孪弈弭拏昫胄胤茗陝𱕻囿洵紇逅陟𩑋䂞俎剋宥庠斫昶柘洌皅砭祐祚荥轱迺郢呲垧敃昝昬昴朐殄毖毘洹狊珉砉祜祢羿胍茴莒虺逄𠖇
    10: 都𭥴個家冓能高部員馬時原這起«29»通骨𤇾真連展𥁕被海隻特莫哥條務書氣造害流样埋格校倠容晒料病拿候記离消𡨄袁资般笑留配根倉班島射鬥效益師竞訓案息难乘尃隺挙速兼党席破𤰇致鬲華座討准值健旅蚊倒素栽恩宮爱站核缺旁酒航莊称借套谈財𬜯眞紙陪殺索陸捕恐监夏𢼸𣁋針䍃透烈庫热途振钱涉积唐陳秘躬逐弱预徒读𰗣倍衰娘髟従浪𮧮逢桂租哲浮畢帯竝顿冡殊捉诸剛奚浦純罢疾笔恶泰納𠳋𠩵朗荷舀胸徐虑託陷烟粉紛郵𭔰珠恵哭埃宾盍载冢峰桌聂秩陶畜凍玆«26»孫臭郭朔桑𧴪宽秦圆隽祥耕敖狼瓶烕貢陰浸芻𡋵恋拳涂悟烦𢚩眠耗窄倫悔桃俱哩虒浩羔柴翁辱脅烏恭逝扇爹陵烝脆宰衮宴涌框竜紐脂唇晏凌𬐚挨晋晃脈匿悦狹桀閃莉羞脊莎贾盐剖卿紋𦐇娥恕翅丵冤挾倘釘軒剥匪殷栗唆艳莧顽倦剝巸晉耆紡袍㢆逛娟贼峻哨恥豈倚冥𰋣耻畔耸恳𡭴涅砰豹斋虔俸剔姬宵耽耿冧狸屑莽欮栖秤蚕桐浆鬯耘飢㫫晌绢莹倩哺娠峭桓畝蚩紊紗恣窊烘盎盏𰤷涕秧荼莖悍祘凋祟恙朕圃悖皋砳莞笋𣬉䀠倭挐挿涖砧𡌥厝娩挛捎栾痂袅釜娣挈涓畟郸屐桎臬豺𥁑晁桧莘釗隼𬶀亳娑宸恁恚罡耄莆峯晟浹珞荳莢邕㼌倮圄恝挹旃涑畚疳眔秫笄笏脩荸荽莠莪衾逋逑铍𥁓
    11: 旣得國理野𢛳做過專問象教動着麻情貫將悤𢇇勒敢現第羕常進祭區望敕婁設基接著黄責竟商球強票張推從組𦰩𮥶參𤱪寅帶埶曽清深眼章殸處鹿産產率視術族規鄉啫異断副曼啇魚领淮停殹許排宿域授細習終船㒼側移頃假曹執密探隊堇救啚敗康鳥添営略营転堂萑敏訪貨孰随维职盛階培斬距㳟婦黒售崔𬀷欲眾菜措混販患𠁳雪奞脱掉彩银𦰌累隆敝偷堅逮脚唯毫弹偏悪梅軗掛符圈陽粒翏𩵋减尉軟𮍏崩淡寄堆虚頂渐梦梁𭾱乾𡕩猛掂彗惜婆液盗偶晝旋粗紹掘蛋閉悉麥盖崇盘盒萈隐涼庶屚淨啬甜蛇菲訟寂桼鹵掩掃啟旉巢猜娶斜捷晨貧梗䙴菌脫聊𣶒淺剪捨偉悠偽廊涵𠚕惨惟淋釣兜窓颇㣎猫痕𭷆翌涯菊貪偵豙爽笨猪徙淫渠戚勘斎婴捧庸萧逸雀桶粘猎袞萄淘笛𪟊淑啓祸笼堵焉绳悼匙屠脖崖牽笠彫梨婉扈笪绵隋菩萎窒笙彪奢渊眷萌衔𡮂欶彬豚隅窑戛晦敘寇烹粛赦聆阎凰盔菓𥞤堕虖捽梢覓谒啄敍菁菱萃萊庵梵殻貶鄂梧舂婪崗帷猖眯趾𠩺匾渦冕捻敛焊脯犁訣𱁈捺舵唬猗偎匐屛淄疵匮屜梓笺畧萦傀恿惮痔崙梏淅笮逵𧰲偃偪寃掗淖淰缽菡阉鸾啵庾斛旌淙菖豉啐掮涪淥淦渚窕笞萠萸袈躭𫔴㽞勖匏啉捭焐瓠笤笥笱粜聃脘菀菟菬菹萘袴赧逶鄄阋隈隗雩𤕻
    12: 就𦥯道黑發間開最然幾等番曾提無單戠買期景巽敬量落萬集程畫登黃結報朝斯喂運統策答喜勝越費減税强達舄童尞鄕備貴善富联超給復極普裁痛𤔔補割街訴勞飲散援奥博替雄堯違評短属殘創筑厤喬雈雇款項尊飯森渡惡游葉須遇尌𰕎犀温塊硬焦絕掌牌遀兟湖圍測絡董雲敞握智惠遍順彭筆隔雅悲𡩜爲満貿衆惑棄賀媒鲁𢽠寒煮揭䖵尋遗粦滑葬募插裂覚琴歯馮逼賁晴揚御筋菐閒韩湯遅絲揸滋盜軽循稍疏敦棟悶絶朁嵒舒虛貸喪遂惱棋禽貼欺晶棵慨棒滞紫缘蒂棉爺赏趁稀椅寍閏湿猶舜歮堪腊覃惹阔筒葛嫂渴牚傅絜奠腔琪堤喉葡脾雯粥欽寓貳厦斑愧翔詐窝黍猒琳厨媚暑殼焚禍鼎翕逾蛛蛮湘厥掣赐喃焰琼詠脹鈍傘斌辜雁𩾏遏屡棘壺窜阑疎壹缊禄嵌啼棠椎窘筍愕羡琢琵㗊凿棥毳斐棕粤韌扉粟粪惢棱葱孱湛葵跛矞𣈅痣絮嗟惰椰欿琶閑渾遁皓鈔媛揞棧湄琦皖遐鉅淵渝窖飪戟渥颉蜓惺蛤酥崽弼揖葆辇嵐猋祿筏鈞筵萱閔淼湮猥萼葺蛰鄔啻喟焱粞蛔凱揆棗棹湟琮葩詔靓飧馭喑婺嵬掾晷欹焯犍琰甤竦缂耋聒腱葚葭葳蒌蒐詈雱黹𱗐
    13: 會想話新意業與義當豊經解僉路感睘圓数電資䧹蜀睪蒦福際愛賈置照辟搞敫傳詹豦勢農源媽試準較該喿群傾園腦楽歲遠號罪满𣪠幹禁督預亂微𢧜盟雷献鼓愈奧跳楚幕溥暗䖒節𡩧零鉄催溫嗎勤蒙简塞睡夢煩債楼睛遣觜䩗署損触載跡搶雍黽嫌碗亶詩摸傻殿腰煙瑞暖粮摇嗇碎畺廌裏飾搖魂賃赖鈴蓝㐮墓蓋廉漠頓慈滅肅詳稚筹聖賊貇鼠溶鉴频蓄搏愁躲溪碍隠聘酬蒸碑腾塩舅暈腸愚誇𨥫寞歇頑盞裸煌溜雾毀瑟蓮匯楊罩蜂蓬鳩斟蒲肆煞腫頒粵寛靴塘睹瑰遙煎裔叠滥羨奨彙颖獅甄窟筷稣蓉魁靖廈嗚虜嗣溯滔禀閘歆隡缚瑜蒼蛾楷廓煉粲睦剿塢跣鉢碁筮腮虞槐裘𤋱楞遜颓榆蔭痺窩腩溺絹嵩𡕰煥漣𤿺滂豢阙雹嗔煨窠罨蜆誅鈺靳椿楙滌牒蒿煦睢稔稟羣蓆裨誊阖剽戡椽雉搉楫猷稗稜稞筲罧蒯蜇詣鉗鉤骞鳯亷彀愍溘溧碓窣蒡訾鄣
    14: 對實說管種緊齊算関廣㡭麼疑需團精臺察領語監聞厭模構維歌滿銀𠪚圖臧舞蓺説養網㬎輕静適賓赛耤盡愿厲稱端赫翟榮聚遭隨蔵様閣摘複㥯壽𩶷漫豪旗稳漸歴鲜輔僚漁腐酸緒誘綠鼻截徴貌寬斲漏寧奪璃暮漂瘦雑𰯲罰漢弊熊遮爾獄頗銃嘉慕魅幣彰滯敲凳綱酷鳴隣寢誓趙熏緑碧蜜僞匱銅嫩榜蔡辣歉僧鄧嘗雐竭𢾰暢翠滾鄰塾寡寨綜僕蔑綿鄭熙駁䡛舆裹蔽髪魄奬熬塵滬膏蔓鳳暨蔣廖賏磋隧墜兢摺肇褐銜碩摷綽麽箏墮榴蔚裳𮅕寥滲屢歰螂暦霆韶慚摹蔗潢閩夐毓裴䋰箸厮嫖漱蔥睿粽綢誦䲨斡疐閨睽箫蔺赘㕡墊摳暱箇箕綵綺貍睾僭漚瑪蜚箩嗻旖榛槁滷瑤嘏墉夤榫槀槃窨綦豩阚雒
    15: 黎賣𧶠樣選調數請樂影臱德論導题價線暴寫豫確質憂談億課賞靠審標熱潘横衛編熟震靚練鬧輝險趣慮篇層遺衝歐遲劇罷廢齒諸彈餘徵播踏盤範畾樓輪摩撞誰鞋儀窮墨慧慰緩醉潜賛暫鋪緣巤憎徹劍糊慶敷潛賭撒遷撲箭賢撮敵趟豬輩髮噴瑩踪履澁潟膠毅劉颜廚𱔞膚撈撻樊賤澄蝦幢撩罵駕廟廛膝滕毆撥瞢稽邁黙嘼槽霊擒蕉勲憧賦鋒鋭儂寮潭魯歎緝撫穀賜遴蕩樞麃閲鞍蕊皺敻樁磊頡霄耦蕃鋤餒儉蕙噓憨戮槳潦幡磐篆賬畿羯輟撟箴緙蕪豎閱蕨暹潸澋翦遼骹儋槭澍虢𤍾
    16: 學機整縣戰還錢頭營親器龍輸薛辦興激舉褱積獨錯融錄歷賴澤餐靜橋橫醒築辨操獲鬳録勵擇衞燒頼憲默雔衡薄奮壁薬厳擁䦨穌赞磨隱薦羲鋼憶濃凝頻憑盧燕憾霍雕穆錫儒薪曉曇謀翰鍵橙蕭駦諧覧澡颠篤縫縛螢鴨冀勳醜曆篷錦膩頹薩蹄噩墾罹薑擎濁穎樸篩薇薜𫲲彊臻薫薯頰膳鋸霖縕輻霓鮑橘篱霎撿樵篡鍂閹瓢錐黔嬴熹隷寰謁壅薏遽澧熾燔橐盥篙縈閻霏圜廪甑磬篦耨薨韰麇
    17: 講雚點應總聲濟襄擧藏環舊擊壓雖謝闌戲聯臨購鮮繁濱戴賽禮縮霜霝藉牆霞聴翼韱濕儲齋爵趨嬰懇藍魏擠韓臂赢燥蹈穗徽聰闊擰謙龜濫鍊彌虧嚮豁鍾轄薰隸鞠罅濯臀輿糞聳禦龠擘濤糜臆盪縷翳輾鴻孺矯斂曖膺氈螽擢燮謗鮭麋毚甕篸篾糝謄謇謨贅蹇𬒣磴縻繇螫
    18: 題邊轉職斷醫離額藝藥豐織歸雜観翻簡雙擺顔覆壘聶蟲雞鎮擾騎瞿霧獵穫謹懵叢襟繞顏巂擸闖鵝璧釐嚣瓊軀彝翹瀉謾竅黠檻臍藜蹙簪馥檽繭蟮闔闕燹簟鞫
    19: 關羅䜌難識警類嚴願壞贊麗懷辭勸繩簿蘇簽穩鏡贈繰顛瀨顚繫疆懶覇龐鯨攀瀧臘靡韻孽寵疇轎瀕羹蘊蘋醮簾麓蘆羸鏢䩻瀝夒藺獺鏖鵪
    20: 議覺護競黨寶獻鐘觸籍齡贏釋魔譽蘭籌譬耀灌騰壤馨籃飄饒竇纂闡𣫞矍懺罌驀𪑛蘖躅
    21: 歡鐵屬露覽攝霸蠢懼髓辯鑊轟鷄赣鶴鶯囂纍蠡夔儼鐸闢騾齧
    22: 體聽囉彎讀攞疊囊籠邏驕聾灑懿蘿蘸龕巒巖糴鑒穰
    23: 變顯驛戀纖籤蠱攣黴蠲
    24: 觀靈鬭鹽艷鷹釀贛蠶鑫羈衢讒靂
    25: 廳蠻籮
    26: 龥驢釁
    27: 纜
    28: 豔
    29: 鬱
    30: 鸞
    32: 龖
    48: 龘

unsorted_hapax:
   0: ⊖⿰⿱⿲⿳⿴⿵⿶⿷⿸⿹⿺⿻
   1: ㇣𠃉𠃎𬼂
   2: «111»«30»«101»«110»㇅㇋㇎乄𠀀𠁡𠂈𠃏𠄍𠄏𠙴𠤬𬼀𰀫𰍧𰍨
   3: «9»«34»«8»«109»«69»«77»«102»«85»㔿乆乊亼亽亾凢刄夨孒𠀄𠀆𠃒𠃔𠆣𠆥𠓛𠔀𠙵𠚤𠠲𠧒𠫓𡕒𡤼𡯂𡰣𢌬𢎗𢎘𣱱𪜀𪜁𪟨𫝄𫡃𫡏𬺱𬺳𬼖𬼸𭅲𰀰𱍸
   4: «13»«35»«105»«33»«116»«115»«107»«92»㐊㐋㐧㓀㔫㕛㠪㸦丒丮乣亖亣仂仉仐兂刅勼勽匁卐厹尣屲弌弖罓阞𠀈𠀋𠀌𠁾𠃙𠆦𠆧𠓝𠔁𠔃𠔄𠔽𠕀𠘬𠘭𠘯𠙷𠙸𠚪𠚫𠠴𠤭𠥻𠨎𠨐𠨬𠫗𠫘𠬚𠬛𠬜𠬞𠬠𠮚𡈽𡗒𡗓𡗜𡴯𡿧𢀳𢆯𢆰𢎜𢎟𣁬𣂑𣎳𣎴𣦵𣦶𣫬𣬛𣱳𤓯𤓰𤣥𥘅𪟽𫜵𫡅𬺷𬺹𬼆𬽢𭀗𭂩𭂫𭃄𭄞𭅄𭅠𭣔𭺫𰁒𰅭𰋵𰍰𱤻𲋄
   5: «5»«106»⺻㐀㐍㐲㒰㓛㓜㕥㘝㚈㚢㞤㞧㲹丱丼亗仚仛仝仢仧仺伋冎冭凥凧刋匇匜卌卭厇厺厼叏叐叴囘夘夰夳尒尻屳屴屶庂弍戹汄甴肊艻艼邜阤𠀎𠀕𠂀𠂕𠂘𠂞𠂟𠂠𠂡𠃢𠆩𠆫𠆳𠑷𠕄𠕅𠕉𠕵𠕶𠕷𠕸𠘲𠘳𠙹𠙺𠙼𠣏𠥽𠦀𠨯𠫝𠬢𠬦𠮢𠮣𠮧𠮨𡆤𡆦𡉀𡉁𡉄𡔛𡖅𡗚𡗛𡥀𡥂𡭗𡯇𡯊𡰤𡰥𡰦𡳿𡴴𢀵𢁓𢆲𢌮𢌯𢎢𢒂𢖫𢖭𢖱𢦍𣍝𣎵𣎶𣎷𣱵𣱷𣱹𣱼𣱽𤕫𤘔𤮺𤯓𥝌𦉪𦉭𦍍𦫳𦫵𨑏𨙰𪜠𪞖𪠲𪢱𪩲𪵨𫑗𫜸𫞕𫧀𫨂𫲡𫵱𫵲𫵳𬺻𬼈𭀚𭁠𭁳𭍺𭐝𭑧𭑨𭒹𭙏𭤟𭺛𭺜𭼽𮍌𮎛𰀈𰀉𰆰𰉗𰋙𰍩𰰝𱍺𱎛𱏿𱑱𱘦
   6: «3»«121»«59»«96»«104»«118»«78»«99»«81»«63»«4»«41»㐁㐂㐪㐼㒲㓇㓙㓝㔻㕂㕄㕦㚐㚣㜽㞌㞍㞪㞬㞭㠩㡯㢟㣼㫃㫐㬰㱏㲽䇂丠仼伇伒伩凩凪刕卋厊叿吇吒囝圫圯圴圶夛夵夶夻奼尥屾岀帇庅弎弜彶忈忛旫朶氽汆汋汍汎汏汑汣灮灳犱犳犴甪癿肎芃芅芆芇芉芌芑芓芕邠阥阩𠀘𠀚𠀜𠀠𠁦𠂂𠂥𠂨𠂬𠂭𠃤𠃨𠄢𠄣𠆸𠇊𠇍𠇏𠇔𠑹𠕋𠕌𠕎𠕻𠕾𠕿𠖲𠘺𠘻𠚁𠚾𠛄𠠼𠣓𠤮𠤱𠦂𠦃𠦄𠦅𠦍𠨺𠨾𠨿𠫡𠫣𠫤𠬩𠬪𠮮𠮯𠮰𠮲𠮳𠮵𠯃𠯄𠯇𠯊𡆩𡆪𡆫𡆬𡉉𡉊𡉐𡉑𡉓𡉖𡔜𡕖𡕟𡖇𡖈𡖉𡗝𡗡𡗢𡚯𡚱𡚴𡚺𡥄𡦾𡦿𡧄𡧇𡧊𡯎𡰫𡰮𡰱𡰲𡴀𡴂𡵂𡵃𡵄𡵆𡵉𡿩𡿪𡿫𢀛𢁙𢁝𢁟𢇛𢌜𢌰𢎱𢑐𢑑𢓁𢖶𢗀𢦑𢨩𢩭𣁁𣂒𣅀𣎺𣎼𣎽𣏀𣦺𣫭𣲂𣲆𤆅𤆆𤆋𤆌𤕭𤘖𤜭𤯔𤰃𥘈𥝍𦍋𦓤𦥒𦥓𦫷𦫼𦫿𧰧𨙺𨚌𨸀𨸢𪜌𪞘𪟩𪢴𪢶𪤷𪥤𪩣𪫆𪱙𪵩𪵪𫝁𫝢𫡓𫤫𫥁𫧍𫧏𫭙𫯜𫰉𫲵𫹭𫾦𬇗𬐃𬔖𬻀𬻄𬻻𬼉𬽄𬽪𭁆𭅰𭆙𭆨𭆽𭍽𭑃𭗼𭘑𭘒𭥌𭥎𭨘𭭽𭴁𭸵𭺽𮉼𮓱𮕤𮦄𰁦𰃝𰅰𰅱𰆗𰌵𰏒𰗑𰦒𱄿𱏻𱐔𱐕𱒅𱛇𱜢𱝼𱤽
   7: «66»㒴㒵㒶㒷㓠㔷㕯㘮㚓㝎㝐㝑㞎㞱㞵㞷㠻㤀㤋㧍㧎㪯㫒㫕㱑㳂㳉㳊㶣㹞㺯㽖㽗㿝䀏䆑䏎丣伱伹伿佉佊佋佦兎兕凬刜刢刧劯匤卲厎厏叓呄呇呌呏呚囦囧囯圽坌坓坔夿妢宊宍宎宐尨尪尫岕岙巵帋帍庈庒廸廹弅彣忮忺戓戺戼扵扸抂抇抈抐攺攼斈旰旳旵曵杄杊杋杗杘杣杦汖汦汧汫汭汱汵汸沄沔沕沚灷灻狃狇皁盁糺耴肑肜芈芘芚芠芣芧芴芶芺芼芿苂辵迊迍迏阼陁陃𠀤𠀧𠁧𠃬𠄘𠅋𠇗𠇚𠇤𠇦𠇩𠇮𠇽𠇾𠑽𠑾𠑿𠒁𠔍𠖀𠖸𠖼𠘽𠛜𠛢𠡉𠦑𠦒𠧚𠩆𠩈𠩉𠬲𠬸𠯌𠯍𠯑𠯓𠯚𠯣𠯪𠯫𠯭𠯳𡆴𡆵𡆾𡇂𡇆𡉚𡉣𡉤𡉰𡉵𡉸𡉺𡉼𡉿𡔞𡗥𡗩𡗬𡗮𡗱𡗶𡛊𡥈𡥉𡧍𡧎𡧐𡭝𡰶𡴆𡴇𡵖𡵧𡵩𡵫𡵬𡵯𡵱𡵳𡵶𡶀𡿮𡿯𢀜𢁳𢁺𢇦𢌳𢌺𢎀𢎿𢒈𢗑𢗝𢗡𢗦𢗨𢗭𢗰𢗼𢦒𢦙𢨪𢪒𢪘𢪙𢪛𢪫𣅄𣅆𣅋𣅌𣅍𣅑𣅔𣌡𣌢𣍟𣏈𣏉𣏋𣏌𣏏𣏒𣥈𣧄𣲎𣲑𣲙𣲩𣲪𣲭𤆍𤆎𤆗𤓳𤬦𤰖𤰗𤰜𤼦𥁀𥃩𥃫𥃮𥃯𥃰𥎦𥐘𥐛𥘑𥝐𥤤𥤥𥤦𥸦𦉱𦉳𦉴𦒱𦘴𦘶𦬅𦬆𦬊𦬑𧢲𧮫𧺆𨈏𨑃𨑄𨑢𨑦𨑭𨑮𨑲𨑳𨙨𨚡𨚪𨚫𨸲𪜢𪜬𪜭𪜮𪜱𪞏𪞐𪟙𪢾𪩡𪪳𪱳𫔭𫔮𫝕𫝣𫠉𫠨𫠩𫡆𫢑𫨶𫩙𫩜𫩞𫭠𫯝𫯞𫰑𫲷𫲺𫹏𫹯𫻨𬁟𬂝𬇚𬉶𬉸𬉹𬋻𬍑𬜥𬷽𬻏𬽲𬽵𭃡𭆃𭎃𭓟𭕇𭗾𭛞𭟯𭣖𭣢𭣣𭤔𭥐𭮀𭮁𭯺𭶻𮌁𮎟𮓗𮕜𮞅𰀾𰅲𰅳𰅴𰆺𰌞𰍪𰍱𰎋𰠧𰠿𰤳𰨛𰰡𰹲𰿩𱑲𱒋𱖐𱘭𱥺𱱴𲂺
   8: «120»«32»㐩㒺㓣㔙㔽㕁㕞㕺㕻㕿㘠㘳㘴㚔㚖㚗㚻㚼㚿㛁㞐㞑㞺㟀㢱㣇㣘㤁㤅㤐㤕㦰㦲㦿㧝㫄㭊㱚㱛㲎㳎㶨㸓㹜㹨㺳㽵䀐䄪䍐䏔䏙䒔䘚䢸丳亝佫佴佸侁侎侘侙侫兓冐冞冾凮刲刵刼刾劼勆匌匼卥卹卺厒厔叀呥呴囶坣坥坩坫坬坮坸奅奌妬妱妸姁姄姈孥宖屇岝岦岨岪岶岺岽峀廻廼弆徂徃忞忥怐怗怚怽抯抳抺拑斨旹旻旾昃昋昑昒昘昛曶杪杴杸枀枈枒欥欦毟沲沷泃泈泍泜炅炇炗炘牨牪狛玢玧玪瓫畁畂盰矤祅祋秅秇秈秊穸糼羋肏肬肰肶舠苐苖苘苙苚苠苨苪苲苳苶苽苾苿茀茇茋茌茐迡迮迱邿郍靣𠀬𠀭𠄭𠄮𠈄𠈇𠈉𠈗𠈣𠈪𠒃𠒆𠒋𠗀𠗆𠙇𠙉𠛧𠛫𠛱𠛹𠛼𠜊𠤻𠦜𠧠𠧢𠧦𠧧𠩋𠩓𠩕𠫭𠫯𠰓𠰕𠰛𠰞𠰣𠰥𠱀𠱄𡇈𡇋𡇌𡊎𡊙𡊚𡊥𡊦𡊨𡊭𡊮𡊱𡊵𡕢𡘃𡘆𡘊𡛩𡛼𡥚𡧘𡧟𡧢𡧧𡭧𡭨𡱁𡱂𡱅𡱈𡴋𡶇𡶓𡶟𡶣𡶤𡶦𡶩𡿱𡿲𢂇𢂋𢆎𢆻𢇳𢇻𢍀𢍁𢏈𢏏𢒊𢘆𢘤𢦟𢨯𢪿𢫕𢺸𢻻𢼂𣂔𣅜𣅟𣅳𣏔𣏚𣏦𣏰𣏼𣏽𣐀𣐁𣐂𣐇𣢊𣢐𣥏𣥐𣥕𣥖𣥚𣥜𣧋𣲲𤆦𤆬𤆯𤓻𤘆𤘴𤝗𤝚𤝡𤤅𤤋𤰅𤰠𤽇𤿌𥁃𥁄𥃳𥃷𥄁𥎨𥐦𥐧𥘣𥘪𥝕𥝝𥝞𥤧𥤨𥤬𥤱𥩘𥸨𥸩𦉷𦉼𦉾𦍐𦏲𦒳𦓎𦙃𦙊𦙌𦙑𦙚𦙟𦥙𦨈𦨉𦬘𦬞𦬣𦬦𦬪𦬬𦬮𦬰𧆛𧈟𧈠𧗠𧠆𧹘𨐌𨒂𨒒𨒙𨒣𨳇𨸏𨹅𪜹𪟄𪠁𪠆𪠨𪥌𪧈𪪎𪫩𪯢𪯱𪯲𪰊𪰋𪰎𪸓𪻓𫃚𫆀𫇭𫐣𫠭𫤘𫧠𫨈𫩣𫩧𫯢𫰗𫲿𫻩𫼉𫾨𬂣𬅟𬇊𬉻𬙘𬚳𬜦𬮠𭁈𭁴𭃚𭅉𭅑𭅒𭅺𭇎𭇐𭎇𭎊𭎌𭑈𭒽𭔫𭕘𭖒𭚫𭟰𭟲𭠂𭣤𭥒𭥕𭥖𭥗𭩢𭭛𭮃𭴉𭴋𭴎𭶪𭸾𭺲𭺳𮝾𮨶𰁽𰇑𰏤𰏴𰗕𰤔𰥍𰥐𰹈𱑎𱒒𱖔𱛖𱡻𱣀𱪮𱬷𱵼𱺵𱻊𱼧𱽐𱽓𲀥
   9: «93»㑛㑞㓂㓧㓨㓩㔜㕟㖈㘶㘸㚆㚚㛄㝁㝔㝖㞒㞕㡿㢲㢴㣞㤗㪅㰦㲋㲒㳝㳞㶮㽚㿞㿽䀗䀛䀜䀝䂝䆓䆔䆖䊸䍒䍔䏣䑣䒕䖉䖟䢼乹乼亯亰侰侱侻俆俥兗冟凃凾剈匨匩厖厗厙叜呰哏哖垕垥壵奊奓姞姧姯姳宨宩尛峉峑巺帠帣庛庣弇怘恠扃拶挃敀敂旀昚昰昺枲枹柃柖柛柝柤柭柺柾栆桒欪殂沗泚泴洀洆洉洎洏洐洝洟洫洳洴洿浐涏炡炢炰炱炶爼珆珎畎畓癹盇盺眀眂眄眊矦砅砏祍秌秏秔穼穾窂窆竒笀笁粀紂紆羍羑羗耇耉耎胋胐胙舁芔茈茖茘茙茛茟茤茦茺茿荁荂荄荎荑荖荗荿虳虵衂衎觔貟贳郗郚郤陖陗陜鳬𠀷𠁭𠂷𠃴𠅔𠈾𠗏𠗒𠚏𠜒𠜤𠜥𠡠𠣞𠥆𠧪𠨚𠩠𠫰𠫵𠫷𠭃𠱠𠱡𠱭𠱯𠱳𠱸𠱼𡇞𡇟𡋍𡋐𡋑𡋛𡋡𡋣𡔢𡘐𡘑𡘒𡘚𡘜𡥞𡥦𡧩𡧯𡧰𡧱𡧷𡬧𡬫𡱜𡱞𡴎𡶫𡶬𡷇𡷈𢆓𢆔𢇂𢈊𢈍𢈏𢈔𢌴𢍂𢍃𢍄𢍆𢍉𢏔𢏚𢏝𢑚𢒎𢓤𢓥𢘻𢘿𢙅𢙇𢙣𢙥𢦦𢦶𢨿𢬇𢬈𢬊𢼉𣂚𣃥𣄰𣅻𣅼𣅽𣆂𣆉𣆊𣆎𣐉𣐝𣐥𣐩𣢜𣥤𣧢𣭁𣳨𣴎𣴓𤇏𤇕𤇘𤇫𤓽𤓾𤓿𤔄𤔆𤝵𤤔𤤤𤤯𤤴𤯚𤰩𤰫𤰸𤰺𤰻𤱊𤼧𤽈𤽗𥄃𥄈𥄉𥄎𥄕𥄗𥄧𥎩𥎯𥘾𥘿𥙊𥝤𥝯𥝸𥝻𥤹𥩞𥫠𥸬𥸭𥸮𥸲𦊁𦊄𦊆𦊈𦊋𦍑𦏺𦏾𦔹𦘔𦚆𦚉𦚋𦚖𦤀𦤶𦥚𦥛𦬸𦬺𦬾𦭓𦭕𦭞𦭤𦭧𧆜𧆞𧈪𧈸𧈹𧘣𧘴𧟥𧴦𧴧𨊢𨊥𨒨𨛡𨛪𨹧𩠐𪜕𪟆𪠇𪠈𪤹𪥍𪭌𪰑𪰖𪱿𪵻𪽋𪽼𪾋𪿈𪿒𫀄𫀩𫇮𫇰𫊝𫊞𫊥𫋲𫋴𫝎𫞰𫟈𫟯𫡙𫢩𫦪𫨻𫯁𫯂𫳂𫾩𬏝𬐘𬙬𬚓𬜪𬡊𬥎𬮦𬽊𬾐𬾕𭃤𭅋𭇥𭎘𭎙𭓩𭓯𭕛𭖚𭘍𭚖𭚬𭛨𭠃𭣩𭤯𭥨𭥫𭥭𭩮𭭟𭰍𭴔𭺾𭺿𭼿𭾡𭾢𮂱𮂸𮃹𮉰𮎰𮓛𮓷𮙥𮥴𮧯𮩴𰀎𰄯𰆄𰆙𰋿𰌼𰑓𰓞𰙠𰙡𰠛𰠭𰥓𰦫𰩬𰫘𰮒𰴨𰴩𰶱𱀋𱅐𱏴𱒛𱒢𱕺𱕼𱖤𱙎𱚠𱛢𱝠𱦊𱪲𱪵𱰭𱲋𱺸𱻲𱽗
   10: «119»㑥㑫㓒㓯㕋㕍㕖㖖㝚㤪㪉㪿㫥㫧㫬㫭㬵㭝㰪㱿㳭㶷㻂㽜㿟㿾䉼䎡䎳䏧䒚䒝䒤䒥䖍䘐䙳䙷䢖䣅俶俻倀倅倐倓倗倝倶冣凊剗剡勑卨厞叞哠哢哿唄圂圅垷埀埐夎娏娕娧娳宭宷宻宼屓屖峩峲峳峷帬庯彧恖恧悁悎扄扅扆挼捃捔捚敇敉斊旂旄曺曻枽栝栞栢栱桊桍桝梃欬欯欱歬毣毦洍浗浛浝浡浧浰浱浼浽浿涄烋烓烜牂牷狶狺珡珤珦珧甡畕畗畠盌眗眘眚眛眜眣眧秝秥秮窅窇窋竘竛笍笒笓粆粍紏紝紦缼羘羙耊耼聀聁肁胷脋荾莀莁莑莗莙莝莟莤莨莩莭蚉蚔袪訔訖貣軎軏軓辂逌郰釛釡閅陮龨鿄𠂹𠂺𠂽𠅖𠅘𠅜𠅝𠊅𠊋𠒖𠓭𠖏𠖐𠙖𠚒𠡷𠣦𠣧𠣬𠥶𠧴𠩬𠩲𠫹𠫼𠲯𠳄𠳅𠳒𠳬𠳮𠳯𠳺𡇢𡋰𡋲𡌓𡔧𡕚𡕦𡘝𡘞𡘤𡘩𡘰𡘲𡘳𡝌𡥨𡨈𡨋𡨐𡨚𡨝𡨞𡨟𡴘𡷝𡷰𡷾𡸁𡸄𢀡𢃄𢃋𢆙𢇁𢇅𢈙𢈱𢍍𢍏𢑛𢓭𢓰𢓱𢔀𢙽𢚘𢚛𢚸𢦷𢭎𢭳𢼜𢼡𢼧𢼴𣂜𣆗𣆟𣆪𣆫𣍮𣐸𣐺𣐽𣑦𣑩𣑽𣪈𣪊𣬈𣴠𣵀𣵎𣵠𣵡𣵣𣷚𤇯𤇷𤇸𤈕𤈜𤔌𤕺𤞻𤤿𤯅𤯟𤱍𤵶𤼩𤽤𥁘𥁫𥄱𥄲𥄳𥄷𥅌𥅘𥎵𥑟𥑥𥑭𥞊𥞓𥞔𥥍𥥐𥥗𥥛𥥟𥩥𥩮𥬄𥬇𥸷𥾸𦊎𦊒𦊚𦊜𦊥𦍤𦒿𦕂𦕈𦚟𦚣𦚧𦚶𦚾𦣣𦤃𦨚𦭶𦮋𦮎𦮔𦮕𦮠𦮴𧆠𧉊𧉎𧉏𧉘𧙃𧙍𧙏𧟨𧥢𧥥𧥧𧮭𧯜𧰬𧲣𧴫𧴮𧴲𨊫𨊰𨓜𨓤𨛼𨤏𨤾𨳌𨺅𩇧𪝉𪞁𪠋𪣣𪧐𪯌𪶀𪸥𪺮𪺽𫂵𫆁𫊫𫐩𫕄𫝗𫝤𫟎𫢴𫦂𫩁𫪉𫳇𫵼𫸚𫸳𫹔𫺁𫼋𫾬𬀴𬁼𬂧𬆣𬊇𬒴𬓥𬔰𬙜𬙮𬜲𬜶𬜷𬬺𬯁𬺞𬻞𬾨𭆆𭆞𭍠𭕞𭖦𭖨𭘧𭙜𭙡𭜨𭜪𭜫𭜮𭜵𭣯𭣱𭤶𭥯𭦃𭩶𭪂𭭇𭭉𭭋𭮩𭮪𭮫𭮬𭯍𭰘𭻉𭽎𭿷𮈄𮊀𮊂𮍦𮎁𮏄𮓸𮕩𮜿𮠚𮥆𮩸𮫮𮮑𰀒𰀕𰀦𰄔𰇩𰉯𰙤𰙩𰛖𰛷𰞚𰢱𰦖𰫝𰭍𰯯𰲚𰺅𱒦𱒱𱖪𱛩𱥂𱦋𱦝𱰮𱳛
   11: 㓱㕘㝛㝝㝠㝡㢈㣦㤲㤻㪍㪷㭪㭬㭰㰯㲘㳫㳿㴆㴌㶾㷀㸔㹿㻎㿡䀁䂮䄅䅆䅇䅈䆟䆠䇠䇣䇤䇥䋈䍘䎆䏻䒦䒩䖏䖤䚴䚵䚺䚻䚿䝆䝨䟝䢙䧑䧔亀偒偘偸偹冨剬剭勔勗厠厡叄唫唻圇圉圊埜堃堊奜婏寀寁寉崑崟崬庳庴庻徛徝徤悊悘悥惈戜戝捼掎掽敓敔斍旈旍晘晜晡晢晧朙桮梄梔梖梞梟梩梫棻欵欷殍涷淂淗淜淠淩淶淸渂渃渄渒烾焄焅焇焏猄猉猚玈琇琍甛畣畤畨皐眽砦硃禼窐窔笘笡笯笴紨紬紵絁絅絇罣脛脣莾菆菉菛菫菳菴菶菿萁萅萆萗萵虗虘衒覔訥谻貮赉赥軖軝逨逩逴逹鄊酓酖镺閆閈隂隌髙𠁁𠁃𠁅𠃀𠊰𠊳𠋛𠋣𠕠𠗦𠚖𠝣𠝭𠝮𠝻𠣯𠦪𠦬𠧸𠪂𠭖𠭙𠵂𠵊𠵛𠵥𠵦𠵨𠶋𠶬𠶮𠶶𡇶𡈀𡌦𡌭𡌳𡍏𡕨𡘷𡘹𡘺𡘼𡘽𡙁𡙆𡝤𡝼𡞔𡞕𡥵𡨤𡨥𡨦𡨧𡨴𡨼𡭽𡮁𡲇𡹐𡿿𢈻𢉅𢉆𢉉𢉖𢉙𢒗𢔃𢔜𢛓𢛢𢛧𢛲𢜈𢜊𢜏𢜤𢧁𢼾𢽊𢽋𢽐𣁐𣂞𣂫𣇀𣇃𣇄𣇓𣇛𣓀𣢾𣣅𣥶𣨑𣪌𣪍𣪏𣪓𣪘𣭵𣶃𣶙𣷌𤈫𤈿𤉄𤉋𤉐𤋳𤕽𤙭𤫶𤭃𤰈𤱵𤱺𤼭𤿤𥁞𥁠𥅥𥆁𥎽𥎿𥏇𥑴𥒐𥒥𥙷𥞫𥥪𥥭𥥴𥬑𥬒𥬝𥬟𥬥𥹙𥿄𦊷𦕒𦕓𦘕𦛱𦤎𦤏𦧔𦯆𦯕𦯧𦯬𦰟𦰧𧆥𧆨𧆩𧆭𧉥𧉴𧉾𧙯𧙿𧟪𧠓𧦈𧦊𧦗𧯞𧰮𧴴𧴵𧴹𧴻𧴿𧵆𧿭𨈡𨊴𨊿𨋅𨓿𨔍𨔛𨜞𨟻𨟽𨤐𨤑𨱝𨱥𨳐𨺵𨾈𨾎𨾏𩁹𩁿𩂀𩇫𩚇𪎊𪡒𪦾𪯍𪲓𪲖𪺏𪺞𫁹𫃟𫇿𫈅𫈏𫏳𫞫𫟐𫤰𫧉𫩀𫪡𫭋𫱀𫳐𫵠𫻶𫽚𫾶𬀽𬂴𬋩𬍥𬑔𬜻𬝉𬦈𬯆𭄶𭍥𭓶𭚽𭜳𭣴𭦊𭦌𭦗𭪗𭴷𭶰𭸋𭻍𭽀𭽪𭾁𭾬𭾲𮋛𮌔𮍖𮏓𮏖𮏚𮏝𮔀𮕱𮖿𮙲𮙸𮞨𮫬𮭱𮮠𰂙𰇶𰓶𰗧𰚋𰠀𰥞𰥡𰨥𰭌𰮕𰱃𰱅𰲛𰲝𰶳𰶵𰶷𰺵𰿘𰿚𱀚𱉥𱏧𱑏𱡘𱥗𱫌𱮇𱰋𱻱
   12: 㑴㑹㓕㔸㖾㙓㛮㜀㝢㝹㞚㟯㠭㡬㢏㣫㥞㥥㦸㨗㪔㪘㪙㪚㫷㫺㫿㮃㮈㮊㰳㱕㲂㲃㲜㴖㴠㷅㷊㻚䂓䄈䅎䆣䆤䆥䇨䇪䊆䎜䏽䏾䐌䑬䒱䒸䒹䒺䓀䓁䖭䘖䘮䙵䜭䟫䠶䦎䧘䨿䭴傌傕僃兠凖剴勛叅喆喦喭嗢圌堛堶堹奡奣媞媠寋寑寔寕嵓嵗廆廋彘徥徧徫悳悹惪惸愄愔戞戢掔揂揔揾敧斝斮旑晱晻暏朞棃棊棐棓棤棨棸棼椂椉椑楇欻欼殽殾淾渙渜渧渫渻湅湆湌湏湔湜湡湳湼溂焛焝焞焣焭焴焸煑牋犂犇猌猭猲琹甯畬畱痗痩皕盙睂睆矟硠硯祼稂稈稊稌窙笿筄筌筳絙絛絢絫絭絰翚翛聑脺脽臦臮臯臰臷臸舃萲萷萹萺葃葅葍葏葑葢葦葴葶葻蒍蓱蛓蛬蜑衖袲裒覘觚訶詋豿貃貰貵赑趂跒軨軫軬軲辝遄酤鈐鈘鈙鈚閕閗隓雋韮頇飭髠𠁊𠔥𠗱𠗲𠞖𠢋𠤤𠥓𠥔𠬁𠭥𠶷𠷎𠷰𠸜𡈂𡈉𡍬𡍮𡍯𡍸𡎐𡔯𡙕𡙗𡞣𡥷𡩋𡩏𡩖𡩘𡩙𡬳𡬵𡬶𡲤𡲫𡺛𡺥𢁅𢁆𢄉𢉲𢉳𢍜𢝔𢝲𢧉𢧐𢰦𢽟𢽬𢽵𢽶𢽹𣁽𣂪𣄃𣈆𣓏𣓕𣓪𣔂𣔋𣣖𣥿𣦃𣸁𣸸𣸹𤉢𤉭𤉷𤊅𤊙𤊱𤗊𤦡𤭐𤯦𤲅𤲆𥁰𥆝𥆞𥇇𥚎𥚢𥟈𥥽𥦕𥬬𥬯𥬵𥭅𥭋𥹫𥿻𦀎𦊽𦐱𦓔𦕬𦜳𦝃𦝄𦣦𦤑𦥭𦧗𦧚𦨯𦱀𦱄𦱋𦱤𦲸𦲿𧆲𧊒𧚍𧦯𧦱𧦴𧯡𧰷𧵍𧹞𧺷𨈭𨐓𨔶𨔾𨕂𨠠𨥌𨥏𨳚𨳞𨾗𨾜𩂊𩇮𪐗𪠮𪧘𪧺𪩃𪯎𪸿𪽗𪿟𪿢𫇆𫏵𫟚𫟛𫣅𫤝𫤪𫤱𫲪𫻹𫾼𬀉𬈆𬈋𬌡𬛥𬛳𬝑𬝘𬡗𬪌𬮈𬮴𬯎𬻨𭀭𭄁𭅍𭆏𭆐𭈹𭡥𭣺𭦟𭪙𭪴𭭎𭭧𭮶𭴺𭾵𮈍𮊿𮕹𮗁𮙺𮞬𮥷𮥹𮦆𮦉𮫙𰗷𰙫𰚢𰞴𰨚𰭢𰷣𰺿𱂥𱋋𱽷
   13: 㗖㙛㙜㚠㝅㨦㨨㬅㮚㮣㰹㰻㲄㴱㴻㷐㷔㼫㼱䀄䁂䅗䅟䇷䇺䇾䇿䋠䋣䋦䍛䍜䐑䑓䓊䝉䝱䡔䢅䢽䣕䣱䧟䪞傫兾剸勠勣厀嗀嗃嗐塋塍壼媐媷媻嫆嫈孴寗寘幐廍弿惷愽搆搕搸摀旒晸暊暐暓暘椹楆楘楢楤楬楺槩歀歃歅歈毼溓溤溦溰溸滈滉滛煔煖煢牑獁甞痯痲痳皵盝睒睗碖禋禓稑稓稕稤窞窡竪筞筨筫筭筴筶綂綈綏綑罬翜腷膄舝艁艂蒕蒖蒤蒩蒪蒭蒮蒹蓁蓍蓐蓽虡衘裊觧詧詵豋豤貈貲賎趍跬跱躳輂輅輈輊辠遘遝遟郒酫酭鈲鈹鉉鉏鉨閙閚閜閞閠阘雺雽頉頊頍飱馵魝鳧鳫鳮麀麁𠅸𠌵𠌶𠍘𠘂𠣻𠦶𠨣𠪔𠪕𠪘𠹈𠹝𡈏𡔲𡔷𡕝𡙢𡠋𡠓𡩟𡩹𡬺𡲬𡺰𡺳𡻎𡻕𢄔𢊁𢊂𢊃𢊆𢊊𢍢𢐌𢔸𢞍𢞭𢟍𢱭𢲛𢽿𢾍𢾕𢾟𣔵𣔾𣕡𣨻𣪧𣮿𣹰𣺎𣺦𣻌𤊸𤊽𤋁𤋃𤋎𤋮𤋯𤕤𤗚𤚖𤠗𤦲𤲢𤷭𤾇𥁼𥂀𥂁𥇘𥇛𥇡𥇨𥇴𥈀𥟦𥦮𥦴𥪖𥭗𥭛𥭭𥭴𥭷𥭽𥹷𥹺𥺀𦀓𦋅𦋐𦎍𦕾𦝚𦝲𦞅𦤔𦥳𦥷𦳃𦳊𦳝𦳪𦴋𦴹𦴼𧆾𧇀𧋠𧠪𧧑𧧬𧱈𧵩𧵽𨋬𨋰𨕞𨕥𨕵𨠭𨥲𨻶𨽶𨾱𩂕𩂜𩉨𩉩𩐁𩑤𩚴𩡱𩰬𩵎𩾕𪝣𪧟𪪷𪫕𪳄𫁒𫁾𫂁𫈦𫈧𫎴𫑨𫖻𫳭𬁅𬆪𬐧𬕍𬥈𬩺𬯻𬿫𭅞𭐖𭔺𭛂𭝤𭤁𭪿𭫄𭵜𭵝𭸢𭿃𮃔𮔉𮖄𮘌𮘎𮮰𮯙𰉒𰙔𰚃𰢅𰲡𱏵𱘥𱢒𲈩𲉜𲊦
   14: 㓗㕑㗬㝬㢕㢡㣃㥷㥽㪡㪣㷠㷦㺒㼲䁔䅠䅡䅥䆫䈁䈇䊍䋲䎩䐜䓗䓢䓤䓧䓨䓬䚂䛟䛣䜹䝳䟽䣈䦚䧻䯉䰟僜僡冩凴勫勭塶塷塹夀奩嫚嫰寠屣嶌幚廔彅愬慁慐慝慟慱戩戫搴搻摠敳暜暠暯曄曅朅榑榖榣榦榼槅槖樋歊歋殞毄滎漅漗漮漻熅熇熒熖牄牓犖獚甍畼瘣皷盠瞍碭磈禛稨稫稭窬竮箄箅箆箋箎箑箒箜綝綮綰綾緂緇緌緐翣膋蓲蓴蓷蓸蓻蓼蔄蔈蔍蔕蔞蔧蔴蜝覞誑誨誩賔踈辡辢遬鄲酼銓銚銛錚閤閧閭閰隤靘鞁馼馽鲞鳶鼏鿿﨎𠃅𠍾𠎤𠎳𠢧𠪨𠪩𠻝𠻮𠼑𠼗𠾧𡏳𡙳𡠺𡡅𡡉𡪛𡬽𡻟𡻦𡻷𡼁𡼇𢇍𢊪𢊬𢒩𢕒𢧤𣂺𣗥𣗪𣘐𣣴𣣸𣣻𣦒𣻢𤌑𤌹𤖏𤛉𤡜𤬌𤯳𤲶𤾊𤾓𥈜𥈠𥈪𥠁𥠖𥪝𥪡𥮗𥯀𥯄𥯌𥺘𥺤𦁉𦁎𦁤𦑕𦖑𦖞𦞧𦞼𦞽𦦀𦩎𦵮𦵯𦵵𦷊𧇃𧇄𧇊𧛱𧟶𧨅𧱏𧱔𧳑𧶉𧶐𨁍𨁡𨐚𨲆𨴠𨾴𩂩𩂫𩢃𩫃𩾦𩾪𩾯𪏭𪓑𪳐𪷁𪷂𫀽𫃅𫄻𫈼𫎇𫒘𫗏𫜩𫡿𫢀𫮛𫯃𫵆𬂉𬃷𬄀𬆭𬈥𬎼𬕏𬕟𬖥𬛭𬡤𭀰𭐫𭔽𭗐𭧂𭫒𭫝𭵠𮄉𮎙𮖐𮥟𮧇𮧊𮮱𰍙𰝂𰮫𰰎𱏬𱢝𱾂𲄡
   15: 㒒㙯㜦㝯㢖㢘㦄㩅㯋㯎㵕㽓㽦䁝䈎䈞䈟䋶䓵䗍䝺䝾䝿䠂䦝䰻䲷䴡䴢僺儇匳厱噐噧墪奭嫴嶚嶲嶴幝廡慙慜慸慼憃憕撜撢撨斳暪槧槮槯槷槾樠歔殢殤潁潐潓潕潗潡潪澑濈濎犘甎皛瞏瞐稸稺窳緘緜緹緼緾罸羮翫翬蕁蕇蕈蕋蕎蕐蕑蕚蕫蕳蝥蝱褢覩諂諄諑豍貎賚賡賫趠踖踷輙輚輦辳遶遹醀醁銽鋂鋞鋠閫閬霅霈韯頝頟頢頣頪鴈鹝鼒𠆆𠏉𠒶𠚛𠾂𠾳𡑅𡔽𡕷𡙷𡙸𡙹𡚁𡡴𡡾𡪺𡼡𢀩𢊸𢒫𢕪𢡃𢧵𢨆𢵄𢵤𢿌𢿐𢿙𢿝𣊖𣙺𣤓𣽨𣾎𤍳𤎉𤕦𤕨𤨝𥂈𥉁𥠷𥡂𥧡𥻆𥻊𥻑𥻡𦂌𦂕𦂝𦂱𦂳𦂺𦋹𦋺𦎧𦎫𦖩𦖻𦟝𦤝𦦉𦸛𦹏𦹚𧇖𧍣𧡖𧣽𧤅𨗉𨤮𨽹𨽻𩃏𩊐𩒛𩒨𩛬𩵢𩾵𩾷𩾹𩿊𪊘𪎷𪏯𪐡𪔅𪧨𪮫𪳝𫉍𫔡𫕙𫯺𬑤𬓶𬙸𬚢𬞕𬢱𬥉𬴘𬹝𬿵𭍳𭐘𭙵𭤊𭧘𭫪𭭔𭮼𭵴𭵼𮐹𮖚𮚋𮥼𰸙𱀵𱿒𲎋
   16: «89»㔍㙶㠔㢛㢣㣈㬜㬱㯤㯥㱅㷴㷼㽔䑞䔍䦧䨜䫉䮍䰜䲽䳆儔儗儞劒劔叡奯嬐嬖孹嶭嶶廧廩彜徼憙懜戱旙暺橆橑橤橦橧毇澰澷燅燊燋燐燚燤獴璚甐疂磟穇穐穒窶窻篗篚篭篹縜縝縠縢缳罃翯聮臈薉薊薎薔薟虣虤螎衟褭褰觱諞諫諬諴諹諼賮踰踶蹀輲辥醖錉錡錿閵閶閼闍頳頴頶頷頺頽餞駡駢駮鴫麆黈𠁗𠔳𠪾𠿊𡕸𡚇𡚊𡦢𡭊𢅛𢍮𢍱𢐨𢕹𢨋𢨒𢿨𢿱𣊡𣚇𣚊𣚨𣚯𣛕𣦞𣫆𣿕𣿳𤎭𤎮𤬏𤯌𤴡𥂔𥉾𥡝𥡞𥰟𥰬𥱋𥱡𥱤𥱩𥻳𦃃𦃐𦃙𦓆𦔐𦠤𦺈𦺸𦻍𦻧𦻱𦻳𦼔𧇨𧇩𧇭𧎪𧎮𧜣𧜼𧳯𧶻𨂠𨂷𨤰𨨖𨽾𨿣𨿳𩃮𩒳𩫏𩰵𩶓𩿳𪉟𪌜𪏰𪏵𪚦𪦨𪫙𫂐𫄾𫕻𫟪𫨀𫴗𬄜𬪰𬹥𭂺𭘸𭟼𭻨𭾐𮃣𮇷𮥿𮧻𮫟𮫴𮭫𰏮𰒲𰕣𰟚𰼝𱅼𱢬𱤏𱹖𲁌
   17: «60»㕓㯱㷿㸂㸃㻺䆸䉅䔘䔡䔥䙔䞿䨣䩭䫏䯹䳒儨壐嬭嶷斁斵檒檗檜歛歜濬獮皤皼磻磿穙穛篲篻篿簋縳縵縶縹縿繄罽膸薲薺薻薾藂藋螻蟄褺謈謟謢谿豳貘賷賸邉醟鍳鎾闇闋闎霛鞞顀顃馘魋鮝鮪鴜鴶鴹黊黚𠮎𡚖𡣍𡽫𡽽𢖍𢣭𢩠𣋓𣫍𤾡𥂮𥂰𥊽𥪴𥱾𥻿𦄐𦄨𦌔𦏁𦒋𦓃𦓈𦗕𦦙𦦚𦼪𦼫𦽦𦾈𦾓𦾔𧝑𧪟𧪬𧫏𧯽𧷏𧷗𧹳𨪆𨵩𩄎𩋘𩫖𩫗𪀲𪏽𪓔𪟺𪪧𫉬𫊣𫏛𫏼𫶝𭄘𭼩𰘴𱢭
   18: 㩥㬥䇔䊩䌛䏈䑂䔲䔵䢯䫕䬕䭉䮕儵嚚奰彞擥旛曛瀐燾爀璹甖礕礜禰竄竆簛簞繒繘繙繠繢罈羴藚藟藪藴虩蠆蹔蹢鎔鎣鎫鎼鏌闒闓闗雝霤鞮韞顒饁馤騐髜鬩鬵鯀鵓鵙鵢鵣麌麏鼀齕龎𠕰𠖥𠨧𡂨𡒲𡗉𡫟𡫥𡴪𡾃𡾏𢇕𢋨𢐴𢐷𣀔𣃍𣄣𣍓𣞈𣫖𤐫𤣂𥜘𥢺𥳑𥼚𦔡𦗟𦪝𦾴𧇽𧑿𧫦𨘢𨟍𨤝𨪈𨶒𨽡𩄣𩄲𩈳𩔇𩔊𩘚𩠬𩡐𩣷𩰿𪊿𪋁𪘂𪤯𫎬𫲓𬙩𬞼𭋷𭔟𭮧𮒛𮒣𮠾𮧡𰌱𱤺𲇖
   19: 㞡㰆㶋䉞䊪䕌䚬䝐䞈䠣䦰䨮䫧䳡匶嚩嚬夓嬾寳廬旟曡櫐櫓櫟瀖爂爊爕犢璽簫簳簷糪繯繴羆羶翽聼臋艶藶蘄蟸蟺蠃覈譖贇蹵鏄鏨闞霪韲顙騜鬊鵭鶂鶄麕鼄龏𡃫𡄉𡖀𢋱𢖙𢸦𢸧𣞤𤛿𤳯𥃆𥣞𥨪𥽂𦆕𧀣𧀨𧁙𧈅𧬉𧸇𨶪𩅜𩌌𩔜𩔪𩸥𩸮𪂣𫠙𫤼𫿞𮆘𮢶𮪍𰘾𰥇
   20: 㒹㜸㶐䊮䕙䢉䨇䫫䳬䶗嚲櫬瀸甗疉籄籊籋羺舋蘥蘦蠒譱轝鐀鐐闥霵顡顢騫騳鶒黁𡾷𣀦𣍘𤳳𥵸𨐼𨶲𩅸𩐋𩐍𩐎𩕆𩪏𩹌𪃍𪚰𪚴𪠛𫬲𬁯𬋝𮋖𰆬
   21: 䕟䕥䦲䳵䵗䵯卛嚻巋廱曩灄禴竈竉籐籖纈罍羼蘷譶贑贔躎躑鐻鑁镾顥驃鬘鰥鷊𠙳𠮓𡈹𢑆𥽘𦇏𧃰𧞻𧭛𧲏𨷈𨷖𩐐𩕍𩕘𩮴𩰥𩺃𪉷𪋘𬮔𮫗𰪠𲌥
   22: 䜟䲆亹孌欎覿讃轡鑍霽鱉鷒鷟齪龝𡿏𣠵𤴁𩁘𩆖𩆞𩦛𩱕𩺯𩺰𪄿𪅀𪅆𪅝𬯵𰥉𱋁
   23: 㸐䶞壨欒籣籥讎讐躘鱗鷸齏𡖂𣡈𤓉𧄼𧅌𧥑𧰟𩕺𩴶𪘨𭨒𱪘
   24: 䕺爤矕雥靃顰鱣黌鼈𠓗𡚤𣡍𣡗𦉥𧅚𩼃𮭘
   25: 欝臠覊鸑黵𣡥𪇠
   26: 飌𠑲𨷷𪇼𱬲
   27: 䕿灥豓鑾𠨋
   28: 钁鸛𰙉𱌦
   30: 爨驫𪙹
   31: 𧟛
   32: 𤴐
   33: 麤𪛈
   36: 䨺